### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [zacg/WordNetAPI#1]
Hi

Just cloned this and ran the TestApplication. Looking up any word results in this exception (shown as a dialog box):

> System.FormatException: Input string was not in a correct format.
>    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
>    at LAIR.ResourceAPIs.WordNet.WordNetEngine.GetSynSetDefinition(POS pos, Int32 offset) in D:\WordNetAPI\src\WordNet\WordNetEngine.cs:line 697
>    at LAIR.ResourceAPIs.WordNet.SynSet.Instantiate() in D:\WordNetAPI\src\WordNet\SynSet.cs:line 180
>    at LAIR.ResourceAPIs.WordNet.WordNetEngine.GetSynSets(String word, POS[] posRestriction) in D:\WordNetAPI\src\WordNet\WordNetEngine.cs:line 631
>    at TestApplication.TestForm.getSynSets_Click(Object sender, EventArgs e) in D:\WordNetAPI\src\TestApplication\TestForm.cs:line 86

Kind regards, Emil

**Comment by ghost** [comment]
However, downloading the most recent database files yields no error :)
